version: '3'
services:
  strapi_app:
    container_name: strapi_app
    build: .
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: FALSE
    volumes:
      - ./app:/srv/app #host volume app
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapi_db
      
  strapi_db:
    container_name: strapi_db
      #platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSGRES_USER}
      POSTGRES_PASSWORD: ${POSGRES_PASSWORD}
      POSTGRES_DB: ${POSGRES_NAME}
    volumes:
      - .db:/var/lib/postgresql/data/ #host volume db
    ports:
      - '5432:5432'
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
